/*
 * SMS API
 *
 * With the Nexmo SMS API you can send SMS from your account and lookup messages both messages that you've sent as well as messages sent to your virtual numbers. Numbers are specified in E.164 format. More SMS API documentation is at <https://developer.nexmo.com/messaging/sms/overview>
 *
 * API version: 1.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sms
// NewMessage struct for NewMessage
type NewMessage struct {
	// Your API key
	ApiKey string `json:"api_key"`
	// Your API secret. Required unless `sig` is provided
	ApiSecret string `json:"api_secret,omitempty"`
	// The hash of the request parameters in alphabetical order, a timestamp and the signature secret. See [Signing Requests](/concepts/guides/signing-messages) for more details.
	Sig string `json:"sig,omitempty"`
	// The name or number the message should be sent from. Alphanumeric senderID's are not supported in all countries, see [Global Messaging](https://developer.nexmo.com/messaging/sms/guides/global-messaging#country-specific-features) for more details. If alphanumeric, spaces will be ignored. Numbers are specified in E.164 format.
	From string `json:"from"`
	// The number that the message should be sent to. Numbers are specified in E.164 format.
	To string `json:"to"`
	// The body of the message being sent. If your message contains characters that can be encoded according to the GSM Standard and Extended tables then you can set the `type` to `text`. If your message contains characters outside this range, then you will need to set the `type` to `unicode`.
	Text string `json:"text,omitempty"`
	// **Advanced**: The duration in milliseconds the delivery of an SMS will be attempted.§§ By default Nexmo attempt delivery for 72 hours, however the maximum effective value depends on the operator and is typically 24 - 48 hours. We recommend this value should be kept at its default or at least 30 minutes.
	Ttl int32 `json:"ttl,omitempty"`
	// **Advanced**: Boolean indicating if you like to receive a [Delivery Receipt](https://developer.nexmo.com/messaging/sms/building-blocks/receive-a-delivery-receipt).
	StatusReportReq bool `json:"status-report-req,omitempty"`
	// **Advanced**: The webhook endpoint the delivery receipt for this sms is sent to. This parameter overrides the webhook endpoint you set in Dashboard.
	Callback string `json:"callback,omitempty"`
	// **Advanced**: The Data Coding Scheme value of the message
	MessageClass int32 `json:"message-class,omitempty"`
	// **Advanced**: The format of the message body
	Type string `json:"type,omitempty"`
	// **Advanced**: A business card in [vCard format](https://en.wikipedia.org/wiki/VCard). Depends on `type` parameter having the value `vcard`.
	Vcard string `json:"vcard,omitempty"`
	// **Advanced**: A calendar event in [vCal format](https://en.wikipedia.org/wiki/VCal). Depends on `type` parameter having the value `vcal`.
	Vcal string `json:"vcal,omitempty"`
	// **Advanced**: Hex encoded binary data. Depends on `type` parameter having the value `binary`.
	Body string `json:"body,omitempty"`
	// **Advanced**: Your custom Hex encoded [User Data Header](https://en.wikipedia.org/wiki/User_Data_Header). Depends on `type` parameter having the value `binary`.
	Udh string `json:"udh,omitempty"`
	// **Advanced**: The value of the [protocol identifier](https://en.wikipedia.org/wiki/GSM_03.40#Protocol_Identifier) to use. Ensure that the value is aligned with `udh`.
	ProtocolId int32 `json:"protocol-id,omitempty"`
	// **Advanced**: The title for a wappush SMS. Depends on `type` parameter having the value `wappush`.
	Title string `json:"title,omitempty"`
	// **Advanced**: The URL of your website. Depends on `type` parameter having the value `wappush`.
	Url string `json:"url,omitempty"`
	// **Advanced**: The availability for an SMS in milliseconds. Depends on `type` parameter having the value `wappush`.
	Validity string `json:"validity,omitempty"`
	// **Advanced**: You can optionally include your own reference of up to 40 characters.
	ClientRef string `json:"client-ref,omitempty"`
	// **Advanced**: An optional string used to identify separate accounts using the SMS endpoint for billing purposes. To use this feature, please email [support@nexmo.com](mailto:support@nexmo.com)
	AccountRef string `json:"account-ref,omitempty"`
}
