/*
 * SMS API
 *
 * With the Nexmo SMS API you can send SMS from your account and lookup messages both messages that you've sent as well as messages sent to your virtual numbers. Numbers are specified in E.164 format. More SMS API documentation is at <https://developer.nexmo.com/messaging/sms/overview>
 *
 * API version: 1.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sms
// ErrorMessage struct for ErrorMessage
type ErrorMessage struct {
	// The error status of the message
	Status string `json:"status,omitempty"`
	// The description of the error
	ErrorText string `json:"error-text,omitempty"`
}
