/*
 * SMS API
 *
 * With the Nexmo SMS API you can send SMS from your account and lookup messages both messages that you've sent as well as messages sent to your virtual numbers. Numbers are specified in E.164 format. More SMS API documentation is at <https://developer.nexmo.com/messaging/sms/overview>
 *
 * API version: 1.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sms
// Message struct for Message
type Message struct {
	// The number the message was sent to. Numbers are specified in E.164 format.
	To string `json:"to,omitempty"`
	// The ID of the message
	MessageId string `json:"message-id,omitempty"`
	// The status of the message. See [Troubleshooting Failed SMS](https://developer.nexmo.com/messaging/sms/guides/troubleshooting-sms).
	Status string `json:"status,omitempty"`
	// Your remaining balance
	RemainingBalance string `json:"remaining-balance,omitempty"`
	// The cost of the message
	MessagePrice string `json:"message-price,omitempty"`
	// The ID of the network of the recipient
	Network string `json:"network,omitempty"`
	// **Advanced**: An optional string used to identify separate accounts using the SMS endpoint for billing purposes. To use this feature, please email [support@nexmo.com](mailto:support@nexmo.com)
	AccountRef string `json:"account-ref,omitempty"`
}
