/*
 * Application API
 *
 * Nexmo provides an Application API to allow management of your Nexmo Applications.  This API is backwards compatible with version 1. Applications created using version 1 of the API can also be managed using version 2 (this version) of the API. 
 *
 * API version: 2.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package application
// ApplicationResponseCapabilities Configuration for the products available in this application
type ApplicationResponseCapabilities struct {
	Voice ApplicationResponseCapabilitiesVoice `json:"voice,omitempty"`
	Messages ApplicationResponseCapabilitiesMessages `json:"messages,omitempty"`
	Rtc ApplicationResponseCapabilitiesRtc `json:"rtc,omitempty"`
	// Specify the `vbc` capability to enable zero-rated calls for VBC number programmability service applications. This is always an empty object.
	Vbc map[string]interface{} `json:"vbc,omitempty"`
}
