/*
 * Application API
 *
 * Nexmo provides an Application API to allow management of your Nexmo Applications.  This API is backwards compatible with version 1. Applications created using version 1 of the API can also be managed using version 2 (this version) of the API. 
 *
 * API version: 2.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package application
// ApplicationResponseCapabilitiesVoiceWebhooksAnswerUrl struct for ApplicationResponseCapabilitiesVoiceWebhooksAnswerUrl
type ApplicationResponseCapabilitiesVoiceWebhooksAnswerUrl struct {
	// The URL that Nexmo requests when a call is placed/received. Must return an NCCO
	Address string `json:"address,omitempty"`
	// The HTTP method used to fetch your NCCO from your `answer_url`
	HttpMethod string `json:"http_method,omitempty"`
}
