/*
 * Application API
 *
 * Nexmo provides an Application API to allow management of your Nexmo Applications.  This API is backwards compatible with version 1. Applications created using version 1 of the API can also be managed using version 2 (this version) of the API. 
 *
 * API version: 2.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package application
// ApplicationResponseCollection struct for ApplicationResponseCollection
type ApplicationResponseCollection struct {
	// The number of applications per page
	PageSize int32 `json:"page_size,omitempty"`
	// The current page number (starts at 1)
	Page int32 `json:"page,omitempty"`
	// The total number of applications
	TotalItems int32 `json:"total_items,omitempty"`
	// The total number of pages returned
	TotalPages int32 `json:"total_pages,omitempty"`
	Embedded ApplicationResponseCollectionEmbedded `json:"_embedded,omitempty"`
}
