/*
 * Number Insight API
 *
 * Nexmo's Number Insight API delivers real-time intelligence about the validity, reachability and roaming status of a phone number and tells you how to format the number correctly in your application. There are three levels of Number Insight API available: [Basic, Standard and Advanced](https://developer.nexmo.com/number-insight/overview#basic-standard-and-advanced-apis). The advanced API is available asynchronously as well as synchronously.
 *
 * API version: 1.0.7
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package numberinsight
// NiResponseJsonAdvanced Advanced
type NiResponseJsonAdvanced struct {
	Status NiStandardAdvancedStatus `json:"status"`
	// The status description of your request.
	StatusMessage string `json:"status_message"`
	// The unique identifier for your request. This is a alphanumeric string up to 40 characters.
	RequestId string `json:"request_id"`
	// The `number` in your request in international format.
	InternationalFormatNumber string `json:"international_format_number"`
	// The `number` in your request in the format used by the country the number belongs to.
	NationalFormatNumber string `json:"national_format_number"`
	// Two character country code for `number`. This is in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format.
	CountryCode string `json:"country_code"`
	// Three character country code for `number`. This is in [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) format.
	CountryCodeIso3 string `json:"country_code_iso3"`
	// The full name of the country that `number` is registered in.
	CountryName string `json:"country_name"`
	// The numeric prefix for the country that `number` is registered in.
	CountryPrefix string `json:"country_prefix"`
	// The amount in EUR charged to your account.
	RequestPrice string `json:"request_price,omitempty"`
	// If there is an internal lookup error, the `refund_price` will reflect the lookup price. If `cnam` is requested for a non-US number the `refund_price` will reflect the `cnam` price. If both of these conditions occur, `refund_price` is the sum of the lookup price and `cnam` price.
	RefundPrice string `json:"refund_price,omitempty"`
	// Your account balance in EUR after this request.
	RemainingBalance string `json:"remaining_balance,omitempty"`
	CurrentCarrier NiCurrentCarrierProperties `json:"current_carrier,omitempty"`
	OriginalCarrier NiInitialCarrierProperties `json:"original_carrier,omitempty"`
	// If the user has changed carrier for `number`. The assumed status means that the information supplier has replied to the request but has not said explicitly that the number is ported.
	Ported string `json:"ported,omitempty"`
	Roaming NiRoaming `json:"roaming,omitempty"`
	CallerIdentity NiCallerIdentity `json:"caller_identity,omitempty"`
	// Shows if all information about a phone number has been returned. Possible values:  Code | Text --- | --- 0 | Success 1 | Partial success - some fields populated 2 | Failed 
	LookupOutcome int32 `json:"lookup_outcome,omitempty"`
	// Shows if all information about a phone number has been returned.
	LookupOutcomeMessage string `json:"lookup_outcome_message,omitempty"`
	// Does `number` exist. `unknown` means the number could not be validated. `valid` means the number is valid. `not_valid` means the number is not valid. `inferred_not_valid` means that the number could not be determined as valid or invalid via an external system and the best guess is that the number is invalid. This is applicable to mobile numbers only.
	ValidNumber string `json:"valid_number,omitempty"`
	// Can you call `number` now. This is applicable to mobile numbers only.
	Reachable string `json:"reachable,omitempty"`
}
