/*
 * Number Insight API
 *
 * Nexmo's Number Insight API delivers real-time intelligence about the validity, reachability and roaming status of a phone number and tells you how to format the number correctly in your application. There are three levels of Number Insight API available: [Basic, Standard and Advanced](https://developer.nexmo.com/number-insight/overview#basic-standard-and-advanced-apis). The advanced API is available asynchronously as well as synchronously.
 *
 * API version: 1.0.7
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package numberinsight
// NiResponseAsync struct for NiResponseAsync
type NiResponseAsync struct {
	// The unique identifier for your request. This is a alphanumeric string up to 40 characters.
	RequestId string `json:"request_id,omitempty"`
	// The `number` in your request
	Number string `json:"number,omitempty"`
	// Your account balance in EUR after this request.
	RemainingBalance string `json:"remaining_balance,omitempty"`
	// If there is an internal lookup error, the `refund_price` will reflect the lookup price. If `cnam` is requested for a non-US number the `refund_price` will reflect the `cnam` price. If both of these conditions occur, `refund_price` is the sum of the lookup price and `cnam` price.
	RequestPrice  string                   `json:"request_price,omitempty"`
	Status        NiStandardAdvancedStatus `json:"status,omitempty"`
	StatusMessage string                   `json:"error_text,omitempty"`
	// The unique identifier for your request. This is a alphanumeric string up to 40 characters.
}
