/*
 * Number Insight API
 *
 * Nexmo's Number Insight API delivers real-time intelligence about the validity, reachability and roaming status of a phone number and tells you how to format the number correctly in your application. There are three levels of Number Insight API available: [Basic, Standard and Advanced](https://developer.nexmo.com/number-insight/overview#basic-standard-and-advanced-apis). The advanced API is available asynchronously as well as synchronously.
 *
 * API version: 1.0.7
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package numberinsight
// NiRoaming Information about the roaming status for `number`. This is applicable to mobile numbers only.
type NiRoaming struct {
	// Is `number` outside its home carrier network.
	Status string `json:"status,omitempty"`
	// If `number` is `roaming`, this is the [code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the country `number` is roaming in.
	RoamingCountryCode string `json:"roaming_country_code,omitempty"`
	// If `number` is `roaming`, this is the id of the carrier network `number` is roaming in.
	RoamingNetworkCode string `json:"roaming_network_code,omitempty"`
	// If `number` is `roaming`, this is the name of the carrier network `number` is roaming in.
	RoamingNetworkName string `json:"roaming_network_name,omitempty"`
}
