/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// Success struct for Success
type Success struct {
	ErrorCode *interface{} `json:"error-code,omitempty"`
	ErrorCodeLabel *interface{} `json:"error-code-label,omitempty"`
}
