/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// SecretMgmtLinks Links related to this resource
type SecretMgmtLinks struct {
	Self SecretMgmtLinksSelf `json:"self,omitempty"`
}
