/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// SecretMgmtLinksSelf This resource
type SecretMgmtLinksSelf struct {
	// The URI for this resource
	Href string `json:"href,omitempty"`
}
