/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// AccountSettings struct for AccountSettings
type AccountSettings struct {
	// The current or updated inbound message URI
	MoCallbackUrl string `json:"mo-callback-url,omitempty"`
	// The current or updated delivery receipt URI
	DrCallbackUrl string `json:"dr-callback-url,omitempty"`
	// The maximum number of outbound messages per second.
	MaxOutboundRequest int32 `json:"max-outbound-request,omitempty"`
	// The maximum number of inbound messages per second.
	MaxInboundRequest int32 `json:"max-inbound-request,omitempty"`
	// The maximum number of API calls per second.
	MaxCallsPerSecond int32 `json:"max-calls-per-second,omitempty"`
}
