/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// SecretInfo struct for SecretInfo
type SecretInfo struct {
	Links SecretMgmtLinks `json:"_links,omitempty"`
	// Secret ID
	Id string `json:"id,omitempty"`
	// Creation date/time for this secret
	CreatedAt string `json:"created_at,omitempty"`
}
