/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// TopupRequest struct for TopupRequest
type TopupRequest struct {
	// The transaction reference of the transaction when balance was added and auto-reload was enabled on your account.
	Trx string `json:"trx"`
}
