/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// AccountSettingsRequest struct for AccountSettingsRequest
type AccountSettingsRequest struct {
	// The URL where Vonage will send a webhook when an SMS is received to a Vonage number that does not have SMS handling configured. Send an empty string to unset this value.
	MoCallBackUrl string `json:"moCallBackUrl,omitempty"`
	// The URL where Vonage will send a webhook when an delivery receipt is received without a specific callback URL configured. Send an empty string to unset this value.
	DrCallBackUrl string `json:"drCallBackUrl,omitempty"`
}
