/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// AccountBalance struct for AccountBalance
type AccountBalance struct {
	// The balance of the account, in EUR
	Value float32 `json:"value,omitempty"`
	// Whether the account has auto-reloading enabled
	AutoReload bool `json:"autoReload,omitempty"`
}
