/*
 * Account API
 *
 * Enables users to manage their Vonage API Account by programmable means. More information is available here: <https://developer.nexmo.com/account/overview>.
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package account
// ErrorApiKeyNotFound This API key was not recognised
type ErrorApiKeyNotFound struct {
	// URL for further information
	Type string `json:"type"`
	// Description of the error
	Title string `json:"title"`
	// More detail regarding this error, including the API key supplied
	Detail string `json:"detail"`
	// Internal Trace ID
	Instance string `json:"instance"`
}
