/*
 * Number Insight API
 *
 * Nexmo's Number Insight API delivers real-time intelligence about the validity, reachability and roaming status of a phone number and tells you how to format the number correctly in your application. There are three levels of Number Insight API available: [Basic, Standard and Advanced](https://developer.nexmo.com/number-insight/overview#basic-standard-and-advanced-apis). The advanced API is available asynchronously as well as synchronously.
 *
 * API version: 1.0.7
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package numberInsight
// NiResponseJsonBasic struct for NiResponseJsonBasic
type NiResponseJsonBasic struct {
	Status NiBasicStatus `json:"status,omitempty"`
	// The status description of your request.
	StatusMessage string `json:"status_message,omitempty"`
	// The unique identifier for your request. This is a alphanumeric string up to 40 characters.
	RequestId string `json:"request_id,omitempty"`
	// The `number` in your request in international format.
	InternationalFormatNumber string `json:"international_format_number,omitempty"`
	// The `number` in your request in the format used by the country the number belongs to.
	NationalFormatNumber string `json:"national_format_number,omitempty"`
	// Two character country code for `number`. This is in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format.
	CountryCode string `json:"country_code,omitempty"`
	// Three character country code for `number`. This is in [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) format.
	CountryCodeIso3 string `json:"country_code_iso3,omitempty"`
	// The full name of the country that `number` is registered in.
	CountryName string `json:"country_name,omitempty"`
	// The numeric prefix for the country that `number` is registered in.
	CountryPrefix string `json:"country_prefix,omitempty"`
}
