/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.3.2
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package voice
// UpdateCallRequestTransferAnswerUrlDestination struct for UpdateCallRequestTransferAnswerUrlDestination
type UpdateCallRequestTransferAnswerUrlDestination struct {
	Type string `json:"type"`
	// The URL that Nexmo makes a request to. Must return an NCCO.
	Url []string `json:"url"`
}
