/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.2.6
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// EndpointWebsocketHeaders Details of the Websocket you want to connect to
type EndpointWebsocketHeaders struct {
	// This is an example header. You can provide any headers you may need
	CustomerId string `json:"customer_id,omitempty"`
}
