/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.3.2
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package voice
// UpdateCallRequestEarmuff struct for UpdateCallRequestEarmuff
type UpdateCallRequestEarmuff struct {
	// Prevent the specified UUID from hearing audio
	Action string `json:"action,omitempty"`
}
