/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.2.6
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// VoiceName The voice & language to use
type VoiceName string

// List of voice_name
const (
	SALLI VoiceName = "Salli"
	JOEY VoiceName = "Joey"
	NAJA VoiceName = "Naja"
	MADS VoiceName = "Mads"
	MARLENE VoiceName = "Marlene"
	HANS VoiceName = "Hans"
	NICOLE VoiceName = "Nicole"
	RUSSELL VoiceName = "Russell"
	AMY VoiceName = "Amy"
	BRIAN VoiceName = "Brian"
	EMMA VoiceName = "Emma"
	GERAINT VoiceName = "Geraint"
	GWYNETH VoiceName = "Gwyneth"
	RAVEENA VoiceName = "Raveena"
	CHIPMUNK VoiceName = "Chipmunk"
	ERIC VoiceName = "Eric"
	IVY VoiceName = "Ivy"
	JENNIFER VoiceName = "Jennifer"
	JUSTIN VoiceName = "Justin"
	KENDRA VoiceName = "Kendra"
	KIMBERLY VoiceName = "Kimberly"
	CONCHITA VoiceName = "Conchita"
	ENRIQUE VoiceName = "Enrique"
	PENELOPE VoiceName = "Penelope"
	MIGUEL VoiceName = "Miguel"
	CHANTAL VoiceName = "Chantal"
	CELINE VoiceName = "Celine"
	MATHIEU VoiceName = "Mathieu"
	DORA VoiceName = "Dora"
	KARL VoiceName = "Karl"
	CARLA VoiceName = "Carla"
	GIORGIO VoiceName = "Giorgio"
	LIV VoiceName = "Liv"
	LOTTE VoiceName = "Lotte"
	RUBEN VoiceName = "Ruben"
	AGNIESZKA VoiceName = "Agnieszka"
	JACEK VoiceName = "Jacek"
	EWA VoiceName = "Ewa"
	JAN VoiceName = "Jan"
	MAJA VoiceName = "Maja"
	VITORIA VoiceName = "Vitoria"
	RICARDO VoiceName = "Ricardo"
	CRISTIANO VoiceName = "Cristiano"
	INES VoiceName = "Ines"
	CARMEN VoiceName = "Carmen"
	MAXIM VoiceName = "Maxim"
	TATYANA VoiceName = "Tatyana"
	ASTRID VoiceName = "Astrid"
	FILIZ VoiceName = "Filiz"
	MIZUKI VoiceName = "Mizuki"
	SEOYEON VoiceName = "Seoyeon"
)
