/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.2.6
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StartStreamRequest struct for StartStreamRequest
type StartStreamRequest struct {
	StreamUrl []string `json:"stream_url"`
	// the number of times to play the file, 0 for infinite
	Loop int32 `json:"loop,omitempty"`
	// Set the audio level of the stream in the range `-1 >= level <= 1` with a precision of 0.1. The default value is 0.
	Level string `json:"level,omitempty"`
}
