/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.3.2
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package voice
// EndpointVbcExtension Connect to a VBC extension
type EndpointVbcExtension struct {
	// The type of connection. Must be `vbc`
	Type string `json:"type"`
	Extension string `json:"extension"`
}
