/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.2.9
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package voice
// EndpointSip Connect to a SIP Endpoint
type EndpointSip struct {
	// The type of connection. Must be `sip`
	Type string `json:"type"`
	// The SIP URI to connect to
	Uri string `json:"uri,omitempty"`
}
