/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.2.9
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package voice
import (
	"time"
)
// CallEvent struct for CallEvent
type CallEvent struct {
	// The UUID of the Conversion that the event relates to
	ConversationUuid string `json:"conversation_uuid"`
	// The endpoint you called from. Possible values are the same as `to`.
	To []map[string]interface{} `json:"to"`
	// The endpoint you called from. Possible values are the same as `to`.
	From []map[string]interface{} `json:"from"`
	// The UUID of the call leg that the event relates to
	Uuid string `json:"uuid"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	Status string `json:"status"`
	Direction string `json:"direction,omitempty"`
}
