/*
 * Voice API
 *
 * The Voice API lets you create outbound calls, control in-progress calls and get information about historical calls. More information about the Voice API can be found at <https://developer.nexmo.com/voice/voice-api/overview>.
 *
 * API version: 1.2.6
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateCallRequestDestination Required when `action` is `transfer`
type UpdateCallRequestDestination struct {
	// Always `ncco`
	Type string `json:"type,omitempty"`
	// The URL that Nexmo makes a request to. Must return an NCCO.
	Url []string `json:"url,omitempty"`
	// Can be used instead of `url` for the `transfer` action only.
	Ncco []map[string]interface{} `json:"ncco,omitempty"`
}
