/*
 * Voice API BETA
 *
 * This is the *beta* version of the Voice API. Calls created with v2 must be managed using [v1 endpoints](/api/voice).  Voice v2 is provided to allow users to create IP calls. If you do not have this requirement we recommend that you stay on v1 for now.  > This API may break backwards compatibility at short notice (60 days) 
 *
 * API version: 2.1.0
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// CallPlacedWebhook struct for CallPlacedWebhook
type CallPlacedWebhook struct {
	// The source of the call
	From string `json:"from,omitempty"`
	// The destination endpoint. This can be a PSTN, SIP, IP or Websocket address
	To string `json:"to,omitempty"`
	// The UUID of the Conversion that the event relates to
	Uuid string `json:"uuid,omitempty"`
	// The UUID of the call leg that the event relates to
	ConversationUuid string `json:"conversation_uuid,omitempty"`
	// The client reference number that the event relates to. This is returned for outbound IP calls instead of a UUID.
	ClientRef string `json:"client_ref,omitempty"`
	Status string `json:"status,omitempty"`
	// Possible values are `outbound` or `inbound`
	Direction string `json:"direction,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
}
