/*
 * Nexmo Verify API
 *
 * The Verify API helps you to implement 2FA (two-factor authentication) in your applications. This is useful for:  * Protecting against spam, by preventing spammers from creating multiple accounts * Monitoring suspicious activity, by forcing an account user to verify ownership of a number * Ensuring that you can reach your users at any time because you have their correct phone number More information is available at <https://developer.nexmo.com/verify>
 *
 * API version: 1.0.11
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package verify
// SearchResponse Success
type SearchResponse struct {
	// The `request_id` that you received in the response to the Verify request and used in the Verify search request.
	RequestId string `json:"request_id,omitempty"`
	// The Nexmo account ID the request was for.
	AccountId string `json:"account_id,omitempty"`
	// Code | Description -- | -- IN PROGRESS | The search is still in progress. SUCCESS | Your user entered a correct verification code. FAILED | Your user entered an incorrect code more than three times. EXPIRED | Your user did not enter a code before the `pin_expiry` time elapsed. CANCELLED | The verification process was cancelled by a Verify control request. 
	Status string `json:"status,omitempty"`
	// The phone number this verification request was used for.
	Number string `json:"number,omitempty"`
	// The cost incurred for this verification request.
	Price string `json:"price,omitempty"`
	// The currency code.
	Currency string `json:"currency,omitempty"`
	// The `sender_id` you provided in the Verify request.
	SenderId string `json:"sender_id,omitempty"`
	// The date and time the verification request was submitted, in the following format YYYY-MM-DD HH:MM:SS.
	DateSubmitted string `json:"date_submitted,omitempty"`
	// The date and time the verification request was completed. This response parameter is in the following format YYYY-MM-DD HH:MM:SS.
	DateFinalized string `json:"date_finalized,omitempty"`
	// The time the first verification attempt was made, in the following format YYYY-MM-DD HH:MM:SS.
	FirstEventDate string `json:"first_event_date,omitempty"`
	// The time the last verification attempt was made, in the following format YYYY-MM-DD HH:MM:SS.
	LastEventDate string `json:"last_event_date,omitempty"`
	// The list of checks made for this verification and their outcomes.
	Checks []SearchResponseChecks `json:"checks,omitempty"`
	// The events that have taken place to verify this number, and their unique identifiers.
	Events []SearchResponseEvents `json:"events,omitempty"`
	// This field may not be present, depending on your pricing model. The value indicates the cost (in EUR) of the calls made and messages sent for the verification process. This value may be updated during and shortly after the request completes because user input events can overlap with message/call events. When this field is present, the total cost of the verification is the sum of this field and the `price` field. 
	EstimatedPriceMessagesSent string `json:"estimated_price_messages_sent,omitempty"`
}
