/*
 * Nexmo Verify API
 *
 * The Verify API helps you to implement 2FA (two-factor authentication) in your applications. This is useful for:  * Protecting against spam, by preventing spammers from creating multiple accounts * Monitoring suspicious activity, by forcing an account user to verify ownership of a number * Ensuring that you can reach your users at any time because you have their correct phone number More information is available at <https://developer.nexmo.com/verify>
 *
 * API version: 1.1.3
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package verify
// SearchResponseChecks struct for SearchResponseChecks
type SearchResponseChecks struct {
	// The date and time this check was received (in the format YYYY-MM-DD HH:MM:SS)
	DateReceived string `json:"date_received,omitempty"`
	// The code supplied with this check request
	Code string `json:"code,omitempty"`
	Status string `json:"status,omitempty"`
	// The IP address, if available (this field is no longer used).
	IpAddress string `json:"ip_address,omitempty"`
}
