/*
 * Nexmo Verify API
 *
 * The Verify API helps you to implement 2FA (two-factor authentication) in your applications. This is useful for:  * Protecting against spam, by preventing spammers from creating multiple accounts * Monitoring suspicious activity, by forcing an account user to verify ownership of a number * Ensuring that you can reach your users at any time because you have their correct phone number More information is available at <https://developer.nexmo.com/verify>
 *
 * API version: 1.1.3
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package verify
// CheckResponse Success
type CheckResponse struct {
	// The `request_id` that you received in the response to the Verify request and used in the Verify check request.
	RequestId string `json:"request_id,omitempty"`
	// The ID of the verification event, such as an SMS or TTS call.
	EventId string `json:"event_id,omitempty"`
	// A value of `0` indicates that your user entered the correct code. If it is non-zero, check the `error_text`.
	Status string `json:"status,omitempty"`
	// The cost incurred for this request.
	Price string `json:"price,omitempty"`
	// The currency code.
	Currency string `json:"currency,omitempty"`
	// This field may not be present, depending on your pricing model. The value indicates the cost (in EUR) of the calls made and messages sent for the verification process. This value may be updated during and shortly after the request completes because user input events can overlap with message/call events. When this field is present, the total cost of the verification is the sum of this field and the `price` field. 
	EstimatedPriceMessagesSent string `json:"estimated_price_messages_sent,omitempty"`
}
