/*
 * Nexmo Verify API
 *
 * The Verify API helps you to implement 2FA (two-factor authentication) in your applications. This is useful for:  * Protecting against spam, by preventing spammers from creating multiple accounts * Monitoring suspicious activity, by forcing an account user to verify ownership of a number * Ensuring that you can reach your users at any time because you have their correct phone number More information is available at <https://developer.nexmo.com/verify>
 *
 * API version: 1.1.3
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package verify
// ControlRequest struct for ControlRequest
type ControlRequest struct {
	// You can find your API key in your [account dashboard](https://dashboard.nexmo.com)
	ApiKey string `json:"api_key"`
	// You can find your API secret in your [account dashboard](https://dashboard.nexmo.com)
	ApiSecret string `json:"api_secret"`
	// The `request_id` you received in the response to the Verify request.
	RequestId string `json:"request_id"`
	// The possible commands are `cancel` to request cancellation of the verification process, or `trigger_next_event` to advance  to the next verification event (if any). Cancellation is only possible 30 seconds after the start of the verification request and before the second event (either TTS or SMS) has taken place.
	Cmd string `json:"cmd"`
}
