/*
 * Application API
 *
 * Nexmo provides an Application API to allow management of your Nexmo Applications.  This API is backwards compatible with version 1. Applications created using version 1 of the API can also be managed using version 2 (this version) of the API. 
 *
 * API version: 2.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package application
// ApplicationResponseCapabilitiesMessagesWebhooksInboundUrl struct for ApplicationResponseCapabilitiesMessagesWebhooksInboundUrl
type ApplicationResponseCapabilitiesMessagesWebhooksInboundUrl struct {
	// The URL that Nexmo forwards inbound messages to on your server
	Address string `json:"address,omitempty"`
	// The HTTP method used to send inbound messages to your server
	HttpMethod string `json:"http_method,omitempty"`
}
