/*
 * Numbers API
 *
 * The Numbers API enables you to manage your existing numbers and buy new virtual numbers for use with Nexmo's APIs. Further information is here: <https://developer.nexmo.com/numbers/overview>
 *
 * API version: 1.0.16
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package numbers
// Ownednumber struct for Ownednumber
type Ownednumber struct {
	// The two character country code in ISO 3166-1 alpha-2 format
	Country string `json:"country,omitempty"`
	// An available inbound virtual number.
	Msisdn string `json:"msisdn,omitempty"`
	// The URL of the webhook endpoint that handles inbound messages
	MoHttpUrl string `json:"moHttpUrl,omitempty"`
	// The type of number: `landline`, `landline-toll-free` or `mobile-lvn`
	Type string `json:"type,omitempty"`
	// The capabilities of the number: `SMS` or `VOICE` or `SMS,VOICE`
	Features []string `json:"features,omitempty"`
	// The messages webhook type: always `app`
	MessagesCallbackType string `json:"messagesCallbackType,omitempty"`
	// A Nexmo Application ID
	MessagesCallbackValue string `json:"messagesCallbackValue,omitempty"`
	// The voice webhook type: `sip`, `tel`, or `app`
	VoiceCallbackType string `json:"voiceCallbackType,omitempty"`
	// A SIP URI, telephone number or Application ID
	VoiceCallbackValue string `json:"voiceCallbackValue,omitempty"`
}
