/*
 * Numbers API
 *
 * The Numbers API enables you to manage your existing numbers and buy new virtual numbers for use with Nexmo's APIs. Further information is here: <https://developer.nexmo.com/numbers/overview>
 *
 * API version: 1.0.18
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package numbers
// InlineResponse401 struct for InlineResponse401
type InlineResponse401 struct {
	// A code relating to this error
	ErrorCode string `json:"error-code,omitempty"`
	// Words describing the error that occurred
	ErrorCodeLabel string `json:"error-code-label,omitempty"`
}
